### ISSUE TITLE
MPH wind speed is showing too many places after decimal point

### ISSUE THREAD

**Issue by Plainbroke** [jclarke0000/MMM-MyCalendar#21]
I will attach picture to show what the issue I am having is.
![Problem](https://user-images.githubusercontent.com/52361469/60390156-dec88a80-9a95-11e9-805f-7a2bb0445716.PNG)

**Comment by ryelou** [comment]
FYI you're posting in the MMM-MyCalendar module, not the MMM-MyWeather.  You may want to repost over there.

**Comment by Plainbroke** [comment]
sorry posted in wrong area
