### ISSUE TITLE
Color And Column

### ISSUE THREAD

**Issue by agentJames** [jclarke0000/MMM-MyCalendar#30]
How do you add the color and make the events into 2 column? Like the picture. 
![image](https://user-images.githubusercontent.com/66752757/86972352-a9825e00-c127-11ea-9947-2dfac0976228.png)

**Comment by agentJames** [comment]
What does the CSS file look like to have the same kind of color, fonts, and the other CSS stuff?

**Comment by BLoodConstructions** [comment]
The colors of each calendar is handled by the config.js
`config: {
                                colored: true,
                                calendars: [
                                        {
                                                symbol: "calendar",
                                                url: "",
                                                color: "#00ff00"
                                        }
}`

**Comment by agentJames** [comment]
Color is there it worked but everything is one color. How do I get it to be multi-colored like:
![image](https://user-images.githubusercontent.com/66752757/87182843-c76fd000-c299-11ea-9b0e-4ec5c248cf32.png)

**Comment by BLoodConstructions** [comment]
Every calendar has its own colors. So try to add a second calendar with a different color, like:

`{
                                                symbol: "calendar", // Feiertage
                                                url: "",
                                                color: "#00ff00"
                                        },
                                        {
                                                symbol: "calendar", //SuperShift
                                                url: "",
                                                color: "#ffa90d"
                                        },
                                        {
                                                symbol: "calendar", // Kalender
                                                url: "",
                                                color: "#2cb9d9"
                                        },
                                        {
                                                symbol: "calendar", // AppleSchedule
                                                url: "",
                                                color: "#244a3e"
                                        },
                                        {
                                                symbol: "calendar", // Geburtstage
                                                url: "",
                                                color: "#d52f90"
                                        },
                                        {
                                                symbol: "calendar", // Abfallkalender
                                                url: "",
                                                color: "#805d07"
                                        }`

Mine looks a little different but like this.

![image](https://user-images.githubusercontent.com/30698845/87183492-8356ec80-c2e6-11ea-8325-253c4a4724eb.png)

**Comment by agentJames** [comment]
Thank you it has the multi color and works now. It looks like: 
![image](https://user-images.githubusercontent.com/66752757/87187012-559b8480-c2a1-11ea-8c65-32a1ea429b4b.png)

The only thing is what do I write in the config file to make it 2 columns and how do I remove the United States?

**Comment by BLoodConstructions** [comment]
Never tried the second column. But the United States could be cause ‘showLocation = true’ Try to set it to false. In default configuration it is true.

**Comment by agentJames** [comment]
Since location is not showing, now everything is working and looking the way I wanted. Thanks for your help.

**Comment by BLoodConstructions** [comment]
That’s great. You’re welcome.
