### ISSUE TITLE
HEADER has a different font

### ISSUE THREAD

**Issue by BLoodConstructions** [jclarke0000/MMM-MyCalendar#5]
Hi,
where can I find the option to change the header of the module to the system font? In my case I have a different font than in other modules. Thanxx

**Comment by jclarke0000** [comment]
MMM-MyCalendar doesn't use a custom font for the header.  Something else is affecting it, although I'm not sure what it might be... In any case, you should be able to do address this in your `custom.css` file.  Example:

```
.MMM-MyCalendar header {
  font-family: "Roboto Condensed", sans-serif;
}
```
